version: "3.7"
services:

  jenkins:
    build: docker/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - data:/var/jenkins_home
      - docker-certs:/certs/client:ro
    depends_on:
      - dind
    networks:
      - default

  dind:
    image: docker:dind
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - data:/var/jenkins_home
      - docker-certs:/certs/client
    command: --storage-driver=overlay2
    networks:
      default:
        aliases:
          - docker
    privileged: true

networks:
  default:
    name: jenkins
    driver: bridge 

volumes:
  data:
  docker-certs:

